import { createPlumApiClient, ensureBaseUrl } from "@plum/shared";

export type {
  AttachPlaybackSessionCommand,
  ClientPlaybackCapabilities,
  CreateLibraryPayload,
  CreateUserPayload,
  CredentialsPayload,
  CreatePlaybackSessionPayload,
  MovieDetails,
  DiscoverItem,
  DiscoverLibraryMatch,
  DiscoverMediaType,
  DiscoverResponse,
  DiscoverSearchResponse,
  DiscoverShelf,
  DiscoverTitleDetails,
  DiscoverTitleVideo,
  DetachPlaybackSessionCommand,
  EmbeddedAudioTrack,
  EmbeddedSubtitle,
  HardwareEncodeFormat,
  HomeDashboard,
  IdentifyResult,
  Library,
  LibraryScanActivity,
  LibraryScanActivityEntry,
  LibraryScanFailure,
  LibraryScanStatus,
  LibraryType,
  MetadataArtworkProvider,
  MetadataArtworkProviderStatus,
  MetadataArtworkSettings,
  MetadataArtworkSettingsResponse,
  MatchStatus,
  MediaItem,
  EpisodeMetadataArtworkFetchers,
  PlumWebSocketCommand,
  PlaybackDelivery,
  PlaybackSession,
  PlumWebSocketEvent,
  PosterCandidate,
  PosterCandidatesResponse,
  SearchResponse,
  RecentlyAddedEntry,
  ScanLibraryResult,
  SetPosterSelectionPayload,
  ShowMetadataArtworkFetchers,
  SeriesDetails,
  SeriesSearchResult,
  SetupStatus,
  ShowActionResult,
  ShowDetails,
  Subtitle,
  TranscodingSettings,
  TranscodingSettingsResponse,
  TranscodingSettingsWarning,
  UpdatePlaybackSessionAudioPayload,
  UpdateLibraryPlaybackPreferencesPayload,
  UpdateMediaProgressPayload,
  ManagedUser,
  User,
  UserRole,
  VaapiDecodeCodec,
} from "@plum/shared";

export const BASE_URL = ensureBaseUrl(import.meta.env.VITE_BACKEND_URL as string | undefined);

const client = createPlumApiClient({
  baseUrl: BASE_URL,
  fetch: globalThis.fetch.bind(globalThis),
});

export const {
  getSetupStatus,
  createAdmin,
  createUser,
  login,
  logout,
  getMe,
  listUsers,
  createLibrary,
  getLibraryScanStatus,
  listLibraries,
  updateLibraryPlaybackPreferences,
  startLibraryScan,
  scanLibraryById,
  identifyLibrary,
  fetchSeriesByTmdbId,
  searchLibraryMedia,
  getMovieDetails,
  getShowDetails,
  getDiscover,
  searchDiscover,
  getDiscoverTitleDetails,
  fetchLibraryMedia,
  getHomeDashboard,
  fetchMediaList,
  createPlaybackSession,
  updatePlaybackSessionAudio,
  closePlaybackSession,
  getTranscodingSettings,
  updateTranscodingSettings,
  getMetadataArtworkSettings,
  updateMetadataArtworkSettings,
  getMoviePosterCandidates,
  setMoviePosterSelection,
  resetMoviePosterSelection,
  getShowPosterCandidates,
  setShowPosterSelection,
  resetShowPosterSelection,
  searchSeries,
  refreshShow,
  confirmShow,
  identifyShow,
  updateMediaProgress,
} = client;

export { client as plumApiClient };
