import { createPlumApiClient, ensureBaseUrl } from "@plum/shared";

export type {
  AttachPlaybackSessionCommand,
  ClientPlaybackCapabilities,
  CreateLibraryPayload,
  CredentialsPayload,
  CreatePlaybackSessionPayload,
  MovieDetails,
  DiscoverAcquisition,
  DiscoverItem,
  DiscoverLibraryMatch,
  DiscoverMediaType,
  DiscoverResponse,
  DiscoverSearchResponse,
  DiscoverShelf,
  DiscoverTitleDetails,
  DiscoverTitleVideo,
  DownloadItem,
  DownloadsResponse,
  DetachPlaybackSessionCommand,
  EmbeddedAudioTrack,
  EmbeddedSubtitle,
  HardwareEncodeFormat,
  HomeDashboard,
  IdentifyResult,
  Library,
  LibraryScanActivity,
  LibraryScanActivityEntry,
  LibraryScanStatus,
  LibraryType,
  MetadataArtworkProvider,
  MetadataArtworkProviderStatus,
  MetadataArtworkSettings,
  MetadataArtworkSettingsResponse,
  MatchStatus,
  MediaStackQualityProfileOption,
  MediaStackRootFolderOption,
  MediaStackServiceKind,
  MediaStackServiceSettings,
  MediaStackServiceValidationResult,
  MediaStackSettings,
  MediaStackValidationResult,
  MediaItem,
  EpisodeMetadataArtworkFetchers,
  PlumWebSocketCommand,
  PlaybackDelivery,
  PlaybackTrackMetadata,
  PlaybackSession,
  PlumWebSocketEvent,
  PosterCandidate,
  PosterCandidatesResponse,
  SearchResponse,
  RecentlyAddedEntry,
  ScanLibraryResult,
  SetPosterSelectionPayload,
  ShowMetadataArtworkFetchers,
  SeriesDetails,
  SeriesSearchResult,
  SetupStatus,
  ShowActionResult,
  ShowDetails,
  Subtitle,
  TranscodingSettings,
  TranscodingSettingsResponse,
  TranscodingSettingsWarning,
  UpdatePlaybackSessionAudioPayload,
  UpdateLibraryPlaybackPreferencesPayload,
  UpdateMediaProgressPayload,
  User,
  VaapiDecodeCodec,
} from "@plum/shared";

export const BASE_URL = ensureBaseUrl(import.meta.env.VITE_BACKEND_URL as string | undefined);

const client = createPlumApiClient({
  baseUrl: BASE_URL,
  fetch: globalThis.fetch.bind(globalThis),
});

export const {
  getSetupStatus,
  createAdmin,
  login,
  logout,
  getMe,
  createLibrary,
  getLibraryScanStatus,
  listLibraries,
  updateLibraryPlaybackPreferences,
  startLibraryScan,
  scanLibraryById,
  identifyLibrary,
  fetchSeriesByTmdbId,
  searchLibraryMedia,
  getMovieDetails,
  getShowDetails,
  getDiscover,
  searchDiscover,
  getDiscoverTitleDetails,
  addDiscoverTitle,
  getDownloads,
  fetchLibraryMedia,
  getHomeDashboard,
  fetchMediaList,
  createPlaybackSession,
  refreshPlaybackTracks,
  updatePlaybackSessionAudio,
  closePlaybackSession,
  getTranscodingSettings,
  updateTranscodingSettings,
  getMetadataArtworkSettings,
  getMediaStackSettings,
  updateMediaStackSettings,
  validateMediaStackSettings,
  updateMetadataArtworkSettings,
  getMoviePosterCandidates,
  setMoviePosterSelection,
  resetMoviePosterSelection,
  getShowPosterCandidates,
  setShowPosterSelection,
  resetShowPosterSelection,
  searchSeries,
  refreshShow,
  confirmShow,
  identifyShow,
  updateMediaProgress,
} = client;

export { client as plumApiClient };
