import { createPlumApiClient, ensureBaseUrl } from "@plum/shared";
import type { LibraryMediaPage, MediaItem } from "@plum/shared";

export type {
  AttachPlaybackSessionCommand,
  ClientPlaybackCapabilities,
  ContinueWatchingEntry,
  CreateLibraryPayload,
  CredentialsPayload,
  CreatePlaybackSessionPayload,
  MovieDetails,
  MovieIdentifyPayload,
  MovieSearchResult,
  DiscoverAcquisition,
  DiscoverBrowseCategory,
  DiscoverBrowseResponse,
  DiscoverGenre,
  DiscoverGenresResponse,
  DiscoverItem,
  DiscoverLibraryMatch,
  DiscoverMediaType,
  DiscoverResponse,
  DiscoverSearchResponse,
  DiscoverShelf,
  DiscoverTitleDetails,
  DiscoverTitleVideo,
  DownloadItem,
  DownloadsResponse,
  DetachPlaybackSessionCommand,
  EmbeddedAudioTrack,
  EmbeddedSubtitle,
  HardwareEncodeFormat,
  HomeDashboard,
  IdentifyResult,
  IntroSkipMode,
  Library,
  LibraryMediaPage,
  LibraryPlaybackTracksRefreshResult,
  LibraryScanActivity,
  LibraryScanActivityEntry,
  LibraryScanStatus,
  LibraryType,
  MetadataArtworkProvider,
  MetadataArtworkProviderStatus,
  MetadataArtworkSettings,
  MetadataArtworkSettingsResponse,
  MatchStatus,
  MediaStackQualityProfileOption,
  MediaStackRootFolderOption,
  MediaStackServiceKind,
  MediaStackServiceSettings,
  MediaStackServiceValidationResult,
  MediaStackSettings,
  MediaStackValidationResult,
  MediaItem,
  EpisodeMetadataArtworkFetchers,
  PlumWebSocketCommand,
  PlaybackDelivery,
  PlaybackTrackMetadata,
  PlaybackSession,
  PlumWebSocketEvent,
  PosterCandidate,
  PosterCandidatesResponse,
  SearchResponse,
  RecentlyAddedEntry,
  ScanLibraryResult,
  SetPosterSelectionPayload,
  ShowMetadataArtworkFetchers,
  SeriesDetails,
  SeriesSearchResult,
  SetupStatus,
  ShowActionResult,
  ShowDetails,
  ShowEpisodesResponse,
  ShowSeasonEpisodes,
  Subtitle,
  TranscodingSettings,
  TranscodingSettingsResponse,
  TranscodingSettingsWarning,
  UpdatePlaybackSessionAudioPayload,
  UpdateLibraryPlaybackPreferencesPayload,
  UpdateMediaProgressPayload,
  User,
  VaapiDecodeCodec,
} from "@plum/shared";

export const BASE_URL = ensureBaseUrl(import.meta.env.VITE_BACKEND_URL as string | undefined);

/** When set (typical dev: `http://localhost:8080`), HLS/direct stream URLs use this origin while API + WS can stay on the Vite proxy via {@link BASE_URL}. */
export const PLAYBACK_STREAM_BASE_URL = ensureBaseUrl(
  import.meta.env.VITE_PLAYBACK_STREAM_BASE as string | undefined,
);

const client = createPlumApiClient({
  baseUrl: BASE_URL,
  fetch: globalThis.fetch.bind(globalThis),
});

export const {
  getSetupStatus,
  createAdmin,
  login,
  logout,
  createQuickConnectCode,
  getMe,
  createLibrary,
  getLibraryScanStatus,
  listLibraries,
  updateLibraryPlaybackPreferences,
  startLibraryScan,
  scanLibraryById,
  identifyLibrary,
  fetchSeriesByTmdbId,
  searchLibraryMedia,
  getMovieDetails,
  getShowDetails,
  getShowEpisodes,
  getDiscover,
  getDiscoverGenres,
  browseDiscover,
  searchDiscover,
  getDiscoverTitleDetails,
  addDiscoverTitle,
  getDownloads,
  getHomeDashboard,
  fetchMediaList,
  createPlaybackSession,
  warmEmbeddedSubtitleCaches,
  refreshPlaybackTracks,
  updatePlaybackSessionAudio,
  closePlaybackSession,
  getTranscodingSettings,
  updateTranscodingSettings,
  getMetadataArtworkSettings,
  getMediaStackSettings,
  updateMediaStackSettings,
  validateMediaStackSettings,
  updateMetadataArtworkSettings,
  getMoviePosterCandidates,
  setMoviePosterSelection,
  resetMoviePosterSelection,
  getShowPosterCandidates,
  setShowPosterSelection,
  resetShowPosterSelection,
  searchMovies,
  searchSeries,
  refreshLibraryPlaybackTracks,
  refreshShow,
  confirmShow,
  identifyShow,
  identifyMovie,
  updateMediaProgress,
} = client;

export function fetchLibraryMedia(
  id: number,
  options?: { offset?: number; limit?: number },
): Promise<LibraryMediaPage | MediaItem[]> {
  return client.fetchLibraryMedia(id, options) as Promise<LibraryMediaPage | MediaItem[]>;
}

export { client as plumApiClient };
